package etp;

class JISKeyboardMetrics {
    public static var S_A = new KeyCoordinate(7, 20, "a");
    public static var S_B = new KeyCoordinate(52, 30, "b");
    public static var S_C = new KeyCoordinate(32, 30, "c");
    public static var S_D = new KeyCoordinate(27, 20, "d");
    public static var S_E = new KeyCoordinate(25, 10, "e");
    public static var S_F = new KeyCoordinate(37, 20, "f");
    public static var S_G = new KeyCoordinate(47, 20, "g");
    public static var S_H = new KeyCoordinate(57, 20, "h");
    public static var S_I = new KeyCoordinate(75, 10, "i");
    public static var S_J = new KeyCoordinate(67, 20, "j");
    public static var S_K = new KeyCoordinate(77, 20, "k");
    public static var S_L = new KeyCoordinate(87, 20, "l");
    public static var S_M = new KeyCoordinate(72, 30, "m");
    public static var S_N = new KeyCoordinate(62, 30, "n");
    public static var S_O = new KeyCoordinate(85, 10, "o");
    public static var S_P = new KeyCoordinate(95, 10, "p");
    public static var S_Q = new KeyCoordinate(5, 10, "q");
    public static var S_R = new KeyCoordinate(35, 10, "r");
    public static var S_S = new KeyCoordinate(17, 20, "s");
    public static var S_T = new KeyCoordinate(45, 10, "t");
    public static var S_U = new KeyCoordinate(65, 10, "u");
    public static var S_V = new KeyCoordinate(42, 30, "v");
    public static var S_W = new KeyCoordinate(15, 10, "w");
    public static var S_X = new KeyCoordinate(22, 30, "x");
    public static var S_Y = new KeyCoordinate(55, 10, "y");
    public static var S_Z = new KeyCoordinate(12, 30, "z");
    public static var L_A;
    public static var L_B;
    public static var L_C;
    public static var L_D;
    public static var L_E;
    public static var L_F;
    public static var L_G;
    public static var L_H;
    public static var L_I;
    public static var L_J;
    public static var L_K;
    public static var L_L;
    public static var L_M;
    public static var L_N;
    public static var L_O;
    public static var L_P;
    public static var L_Q;
    public static var L_R;
    public static var L_S;
    public static var L_T;
    public static var L_U;
    public static var L_V;
    public static var L_W;
    public static var L_X;
    public static var L_Y;
    public static var L_Z;
    public static var EXCLAMATION_MARK;
    public static var DOUBLE_QUOTATION_MARK;
    public static var SHARP;
    public static var DOLLAR_SIGN;
    public static var PERCENTAGE;
    public static var AMPERSAND;
    public static var SINGLE_QUOTATION_MARK;
    public static var LEFT_PARENTHESIS;
    public static var RIGHT_PARENTHESIS;
    public static var MINUS = new KeyCoordinate(100, 0, "-");
    public static var EQUAL;
    public static var HAT = new KeyCoordinate(110, 0, "^");
    public static var TILDE;
    public static var PIPE;
    public static var AT_MARK = new KeyCoordinate(105, 10, "@");
    public static var BACK_QUOTE;
    public static var LEFT_SQUARE_BRACKET = new KeyCoordinate(115, 10, "[");
    public static var RIGHT_SQUARE_BRACKET = new KeyCoordinate(117, 20, "]");
    public static var LEFT_BRACE;
    public static var RIGHT_BRACE;
    public static var SEMI_COLON = new KeyCoordinate(97, 20, ";");
    public static var COLON = new KeyCoordinate(107, 20, ":");
    public static var PLUS;
    public static var ASTERISK;
    public static var COMMA = new KeyCoordinate(82, 30, ",");
    public static var PERIOD = new KeyCoordinate(92, 30, ".");
    public static var LEFT_ANGLE_BRACKET;
    public static var RIGHT_ANGLE_BRACKET;
    public static var SLASH = new KeyCoordinate(102, 30, "/");
    public static var QUESTION_MARK;
    public static var BACK_SLASH = new KeyCoordinate(112, 30, "\\");
    public static var UNDER_BAR;
    public static var N_1 = new KeyCoordinate(0, 0, "1");
    public static var N_2 = new KeyCoordinate(10, 0, "2");
    public static var N_3 = new KeyCoordinate(20, 0, "3");
    public static var N_4 = new KeyCoordinate(30, 0, "4");
    public static var N_5 = new KeyCoordinate(40, 0, "5");
    public static var N_6 = new KeyCoordinate(50, 0, "6");
    public static var N_7 = new KeyCoordinate(60, 0, "7");
    public static var N_8 = new KeyCoordinate(70, 0, "8");
    public static var N_9 = new KeyCoordinate(80, 0, "9");
    public static var N_0 = new KeyCoordinate(90, 0, "0");

    public function new() {}
}
